import React from 'react';
import { useRoute, Link } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { getReport } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { ShieldAlert, Download, Printer, ArrowLeft, CheckCircle } from 'lucide-react';

export default function ReportView() {
  const [, params] = useRoute('/investigation/:id/report');
  const investigationId = params?.id ?? '';

  const { data: report, isLoading, error } = useQuery({
    queryKey: ['report', investigationId],
    queryFn: () => getReport(investigationId),
    enabled: !!investigationId,
  });

  if (isLoading) return <div className="p-8 text-center text-muted-foreground">Generating report…</div>;
  if (error || !report?.investigation) return <div className="p-8 text-center">Report not found</div>;

  const investigation = report.investigation;

  return (
    <div className="max-w-4xl mx-auto py-8 animate-in-slide print:p-0 print:max-w-none">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <Link href={`/investigation/${investigation.id}`}>
          <Button variant="ghost" size="sm" className="gap-2">
            <ArrowLeft className="h-4 w-4" /> Back to Investigation
          </Button>
        </Link>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={() => window.print()}>
            <Printer className="mr-2 h-4 w-4" /> Print
          </Button>
          <Button
            size="sm"
            className="bg-primary text-primary-foreground hover:bg-primary/90"
            onClick={() => window.open(`/api/investigations/${investigation.id}/report?format=html`, '_blank')}
          >
            <Download className="mr-2 h-4 w-4" /> Download HTML
          </Button>
        </div>
      </div>

      <Card className="bg-white text-black border-none shadow-xl print:shadow-none min-h-[1100px] relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none flex items-center justify-center opacity-[0.03] z-0">
          <ShieldAlert className="h-[500px] w-[500px]" />
        </div>

        <div className="relative z-10 p-12">
          <div className="flex justify-between items-start border-b-2 border-black pb-8 mb-8">
            <div>
              <h1 className="text-4xl font-bold font-display tracking-tight uppercase">Intelligence Report</h1>
              <p className="text-sm font-mono mt-2 text-gray-600">Generated by Kimi K2 OSINT Platform</p>
            </div>
            <div className="text-right">
              <div className="bg-black text-white px-3 py-1 font-bold font-mono text-sm inline-block mb-2">CONFIDENTIAL</div>
              <p className="text-xs font-mono text-gray-500">REF: {investigation.id.toUpperCase()}</p>
              <p className="text-xs font-mono text-gray-500">{new Date(report.generatedAt).toLocaleDateString()}</p>
            </div>
          </div>

          <section className="mb-8">
            <h2 className="text-xl font-bold uppercase mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-red-600 block"></span>
              Executive Summary
            </h2>
            <div className="bg-gray-50 p-6 border border-gray-200 text-sm leading-relaxed">
              <p className="mb-4">
                Target entity <strong>{investigation.target}</strong> is currently in <strong>{investigation.phase}</strong> with risk score{' '}
                <strong>{investigation.riskScore}/100</strong>.
              </p>
              <div className="grid grid-cols-3 gap-4 mt-6">
                <div className="text-center p-4 bg-white border border-gray-200">
                  <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Risk Score</div>
                  <div className="text-3xl font-bold text-red-600">{investigation.riskScore}/100</div>
                </div>
                <div className="text-center p-4 bg-white border border-gray-200">
                  <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Evidence Items</div>
                  <div className="text-3xl font-bold text-orange-600">{report.summary?.evidenceCount ?? 0}</div>
                </div>
                <div className="text-center p-4 bg-white border border-gray-200">
                  <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Entities</div>
                  <div className="text-3xl font-bold text-blue-600">{report.summary?.entityCount ?? 0}</div>
                </div>
              </div>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold uppercase mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-black block"></span>
              Target Profile
            </h2>
            <div className="grid grid-cols-2 gap-x-8 gap-y-4 text-sm">
              <div className="flex justify-between border-b border-gray-200 pb-2">
                <span className="font-bold text-gray-600">Primary Identifier</span>
                <span className="font-mono">{investigation.target}</span>
              </div>
              <div className="flex justify-between border-b border-gray-200 pb-2">
                <span className="font-bold text-gray-600">Target Type</span>
                <span className="font-mono">{investigation.targetType}</span>
              </div>
              <div className="flex justify-between border-b border-gray-200 pb-2">
                <span className="font-bold text-gray-600">Created</span>
                <span className="font-mono">{new Date(investigation.createdAt).toLocaleString()}</span>
              </div>
              <div className="flex justify-between border-b border-gray-200 pb-2">
                <span className="font-bold text-gray-600">Tasks</span>
                <span className="font-mono">{investigation.completedTasks}/{investigation.totalTasks}</span>
              </div>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold uppercase mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-black block"></span>
              Key Findings (latest evidence)
            </h2>
            <div className="space-y-4">
              {(report.evidence ?? []).slice(0, 6).map((e: any) => (
                <div key={e.id} className="flex gap-4 items-start">
                  <div className="mt-1">
                    <CheckCircle className="h-5 w-5 text-black" />
                  </div>
                  <div>
                    <h3 className="font-bold text-sm">{e.title}</h3>
                    <p className="text-sm text-gray-600 mt-1">
                      Source: <span className="font-mono">{e.source}</span> • Type: <span className="font-mono">{e.type}</span>
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <div className="mt-20 pt-8 border-t border-gray-200 flex justify-between text-[10px] text-gray-400 font-mono uppercase">
            <span>Generated by Kimi OSINT Platform</span>
            <span>Page 1 of 1</span>
          </div>
        </div>
      </Card>
    </div>
  );
}
