import React from 'react';
import { useRoute } from 'wouter';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { ShieldAlert, Download, Printer, ArrowLeft, Globe, Calendar, CheckCircle } from 'lucide-react';
import { useApp } from '@/lib/store';
import { Link } from 'wouter';

export default function ReportView() {
  const [, params] = useRoute('/investigation/:id/report');
  const { investigations } = useApp();
  const investigation = investigations.find(i => i.id === params?.id);

  if (!investigation) return <div className="p-8 text-center">Report not found</div>;

  return (
    <div className="max-w-4xl mx-auto py-8 animate-in-slide print:p-0 print:max-w-none">
      <div className="mb-6 flex items-center justify-between print:hidden">
         <Link href={`/investigation/${investigation.id}`}>
            <Button variant="ghost" size="sm" className="gap-2">
               <ArrowLeft className="h-4 w-4" /> Back to Investigation
            </Button>
         </Link>
         <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={() => window.print()}>
               <Printer className="mr-2 h-4 w-4" /> Print
            </Button>
            <Button size="sm" className="bg-primary text-primary-foreground hover:bg-primary/90">
               <Download className="mr-2 h-4 w-4" /> Download PDF
            </Button>
         </div>
      </div>

      <Card className="bg-white text-black border-none shadow-xl print:shadow-none min-h-[1100px] relative overflow-hidden">
         {/* Watermark */}
         <div className="absolute inset-0 pointer-events-none flex items-center justify-center opacity-[0.03] z-0">
            <ShieldAlert className="h-[500px] w-[500px]" />
         </div>

         <div className="relative z-10 p-12">
            {/* Header */}
            <div className="flex justify-between items-start border-b-2 border-black pb-8 mb-8">
               <div>
                  <h1 className="text-4xl font-bold font-display tracking-tight uppercase">Intelligence Report</h1>
                  <p className="text-sm font-mono mt-2 text-gray-600">Generated by Dpt of Karma OSINT</p>
               </div>
               <div className="text-right">
                  <div className="bg-black text-white px-3 py-1 font-bold font-mono text-sm inline-block mb-2">CONFIDENTIAL</div>
                  <p className="text-xs font-mono text-gray-500">REF: {investigation.id.toUpperCase()}</p>
                  <p className="text-xs font-mono text-gray-500">{new Date().toLocaleDateString()}</p>
               </div>
            </div>

            {/* Executive Summary */}
            <section className="mb-8">
               <h2 className="text-xl font-bold uppercase mb-4 flex items-center gap-2">
                  <span className="w-1 h-6 bg-red-600 block"></span>
                  Executive Summary
               </h2>
               <div className="bg-gray-50 p-6 border border-gray-200 text-sm leading-relaxed">
                  <p className="mb-4">
                     Target entity <strong>{investigation.target}</strong> has been identified as a <strong>High Risk</strong> subject following a Phase 2 Deep Collection operation. 
                     The investigation revealed significant exposure across 3 distinct infrastructure nodes and correlation with known breach datasets.
                  </p>
                  <div className="grid grid-cols-3 gap-4 mt-6">
                     <div className="text-center p-4 bg-white border border-gray-200">
                        <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Confidence</div>
                        <div className="text-3xl font-bold text-black">{(investigation as any).confidence ?? 0}%</div>
                     </div>
                     <div className="text-center p-4 bg-white border border-gray-200">
                        <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Exposure Level</div>
                        <div className="text-3xl font-bold text-orange-600">CRITICAL</div>
                     </div>
                     <div className="text-center p-4 bg-white border border-gray-200">
                        <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">Data Points</div>
                        <div className="text-3xl font-bold text-blue-600">1,204</div>
                     </div>
                  </div>
               </div>
            </section>

            {/* Target Profile */}
            <section className="mb-8">
               <h2 className="text-xl font-bold uppercase mb-4 flex items-center gap-2">
                  <span className="w-1 h-6 bg-black block"></span>
                  Target Profile
               </h2>
               <div className="grid grid-cols-2 gap-x-8 gap-y-4 text-sm">
                  <div className="flex justify-between border-b border-gray-200 pb-2">
                     <span className="font-bold text-gray-600">Primary Identifier</span>
                     <span className="font-mono">{investigation.target}</span>
                  </div>
                  <div className="flex justify-between border-b border-gray-200 pb-2">
                     <span className="font-bold text-gray-600">Classification</span>
                     <span className="font-mono">HOSTILE_INFRASTRUCTURE</span>
                  </div>
                  <div className="flex justify-between border-b border-gray-200 pb-2">
                     <span className="font-bold text-gray-600">First Seen</span>
                     <span className="font-mono">2023-11-12</span>
                  </div>
                  <div className="flex justify-between border-b border-gray-200 pb-2">
                     <span className="font-bold text-gray-600">Last Active</span>
                     <span className="font-mono text-green-600">Active Now</span>
                  </div>
               </div>
            </section>

            {/* Findings */}
            <section className="mb-8">
               <h2 className="text-xl font-bold uppercase mb-4 flex items-center gap-2">
                  <span className="w-1 h-6 bg-black block"></span>
                  Key Findings
               </h2>
               <div className="space-y-4">
                  {[1, 2, 3].map((i) => (
                     <div key={i} className="flex gap-4 items-start">
                        <div className="mt-1">
                           <CheckCircle className="h-5 w-5 text-black" />
                        </div>
                        <div>
                           <h3 className="font-bold text-sm">Infrastructure Correlation #{i}</h3>
                           <p className="text-sm text-gray-600 mt-1">
                              Identified direct linkage between target domain and IP range 192.168.1.0/24, previously associated with APT-28 activity groups.
                           </p>
                        </div>
                     </div>
                  ))}
               </div>
            </section>

             {/* Footer */}
            <div className="mt-20 pt-8 border-t border-gray-200 flex justify-between text-[10px] text-gray-400 font-mono uppercase">
               <span>Generated by Dpt of Karma OSINT</span>
               <span>Page 1 of 5</span>
            </div>
         </div>
      </Card>
    </div>
  );
}
